name: omni
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 狀態
  scoped_model: ^1.0.1
  # 本地存储
  shared_preferences: ^0.5.3+4
  # 屏幕适配
  flutter_screenutil: ^0.6.0
  # 接口请求
  dio: ^2.1.13 
  # 上拉加载下拉刷新
  pull_to_refresh: ^1.5.6
    #日期，正则，倒计时，定时任务，时间轴等
  common_utils: ^1.1.3

   # http package https://pub.dartlang.org/packages/http#-readme-tab-
  http: ^0.12.0+2

  cached_network_image: ^1.1.0


  #------------------------
  # Added by Kevin Zhang
  # swiper
  flutter_swiper : ^1.1.4

  # Auto size for text
  auto_size_text: ^1.1.0

  # chart library 
  fcharts: ^0.0.10

  # Add features to the Android / iOS keyboard
  keyboard_actions: ^1.0.3

  # Flutter plugin for selecting images from the Android and iOS image library, 
  # and taking new pictures with the camera.
  image_picker: ^0.6.0+16

  # A collection of loading indicators animated.
  flutter_spinkit: ^3.1.0
  
  # image compress
  flutter_image_compress: ^0.6.3
  #------------------------
  
  # QR.Flutter is a Flutter library for simple and fast QR code rendering via a Widget or custom painter.
  qr_flutter: ^2.0.0+51
  #------------------------
#  flutter_webview_plugin: ^0.3.5

  flutter_slidable: "^0.4.9"

  bip39: ^1.0.3

  bitcoin_flutter: ^1.0.6

  bitcoin_bip44: ^0.1.1

  fluttertoast: ^3.1.0
  #  Flutter plugin to encrypt, decrypt (RSA/ECB/PCSK1), verify and sign string with a public and a private key
  encrypt: ^3.0.0

  url_launcher: ^5.0.2


  

dev_dependencies:
  flutter_test:
    sdk: flutter
 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  # - family: Schyler
  #   fonts:
  #     - asset: fonts/Schyler-Regular.ttf
  #     - asset: fonts/Schyler-Italic.ttf
  #       style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: GothamRnd
      fonts: 
        - asset: fonts/GothamRnd-Book.otf
        - asset: fonts/GothamRnd-Medium.otf
          weight: 600